- package:
  - name: log-classifier
  - section:
    - name: exe:log-classifier-exe
    - message:
      - name: Redundant build-depends entry
      - depends: base
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends:
        - generics-sop
        - reflection
    - message:
      - name: Weeds exported
      - module:
        - name: HttpLayer
        - identifier: emptyHTTPNetworkLayer
  - section:
    - name: test:log-classifier-test
    - message:
      - name: Redundant build-depends entry
      - depends:
        - aeson
        - array
        - attoparsec
        - bytestring
        - containers
        - http-conduit
        - mtl
        - reflection
        - regex-tdfa
        - zip-archive

