status = [
  "buildkite/log-classifier",
  "ci/hydra:serokell:log-classifier:required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
